#!/bin/bash


function csv() {
    column -t -s, -n "$@"
}

usage () {
    echo "$(basename $0) [OPTION] path/to/file.csv
OPTION:
  --field-indices     comma separated list of column index
  --field-names       comma separated list of column names
  --pretty            pretty print the resulting csv"
}

if [ "$#" -eq 0 ]; then
    usage
    exit 0
fi

while [ "$#" -gt 0 ]; do
    case "$1" in
        --field-indices)
            FIELD_INDEX_LIST="$2"
            shift 2
            ;;
        --field-names)
            FIELD_NAME_LIST="$2"
            shift 2
            ;;
        --pretty)
            PRETTY="true"
            shift 1
            ;;
        -h | --help)
            usage
            exit 1
            ;;
        --)
            shift 2
            break
            ;;
        -*)
            echo "Unknown parameter $1"
            exit 1
            ;;
        *)
            usage
            break
            ;;
    esac
done

FILE_PATH="$1"
if [ -z "$FILE_PATH" ]; then
    echo "No file path specified"
    exit 1
fi

if [ ! -z "$FIELD_INDEX_LIST" ] && [ ! -z "$FIELD_NAME_LIST" ]; then
    echo "Cannot specify both options."
    exit 1
fi


my_func() {
    local INDEX_LIST="$1"
    local FILE_PATH="$2"
    if [ "${PRETTY}" == "true" ]; then
        cut -d, -f"$INDEX_LIST" "$FILE_PATH" | csv
    else
        cut -d, -f"$INDEX_LIST" "$FILE_PATH"
    fi
}

if [ ! -z "$FIELD_INDEX_LIST" ]; then
    my_func "$FIELD_INDEX_LIST" "$FILE_PATH"
    exit 0
fi

if [ ! -z "$FIELD_NAME_LIST" ]; then
    declare -a INDEX_LIST
    IFS=',' read -r -a NAME_LIST <<< "$FIELD_NAME_LIST"
    for each in "${NAME_LIST[@]}"
        do
            INDEX_VAL=$(head -n1 "$FILE_PATH" | tr ',' '\n' | grep -n $each | cut -d: -f1)
            INDEX_LIST+=("$INDEX_VAL")
        done
        INDEX_LIST_CSV=`echo $(echo ${INDEX_LIST[@]} | tr ' ' ',')`
        my_func "$INDEX_LIST_CSV" "$FILE_PATH"
fi

